apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: LoadBalancer   # 👈 changed from ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080        # Service port (external)
      targetPort: 8080  # Container port
      protocol: TCP
      name: http
