apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/modern-saga-472703-k3/todo-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: mongodb://mongo-service:27017/

